theme: jekyll-theme-minimal

# Dependencies
#markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Acme Rocket
tagline:          'Field Notes'
description:      'Personal ruminations about technology and what not.'
url:              https://philion.github.io/

author:
  name:           'Paul Philion'
  url:            https://github.com/philion

#paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/philion/philion.github.io
